CREATE TABLE m_user(
id INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20),
PASSWORD VARCHAR(15),
age int
);

INSERT INTO m_user(NAME,PASSWORD,age) VALUES('aa','123',12);
INSERT INTO m_user(NAME,PASSWORD,age) VALUES('bb','1234',13);
INSERT INTO m_user(NAME,PASSWORD,age) VALUES('cc','1235',16);
INSERT INTO m_user(NAME,PASSWORD,age) VALUES('dd','1236',15);
